version: '3.8'

services:
  node_app:
    build:
      context: .
      dockerfile: Dockerfile
      command: yarn start
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    expose:
      - "3000"
